"""Add status to the banner

Revision ID: f2e5793bb48b
Revises: 4cb63a354495
Create Date: 2019-03-14 07:18:46.123675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e5793bb48b'
down_revision = '4cb63a354495'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banners', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banners', 'status')
    # ### end Alembic commands ###
