"""Add status to the banner

Revision ID: ab325248aabb
Revises: f2e5793bb48b
Create Date: 2019-03-14 07:30:05.393009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab325248aabb'
down_revision = 'f2e5793bb48b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
