"""Change status to SmallInteger

Revision ID: d91c2c760308
Revises: ab325248aabb
Create Date: 2019-03-16 06:57:15.379304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91c2c760308'
down_revision = 'ab325248aabb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
