from carusel.models.banner import Banner
import sqlalchemy as sa
from paginate_sqlalchemy import SqlalchemyOrmPage


class CaruselPaginationService():
    def __init__(self, request):
        self.request = request
        self.query = request.dbsession.query(Banner)

    @property
    def all(self):
        return self.query.order_by(sa.desc(Banner.created))

    @property
    def by_title_name(self):
        return self.query.order_by(Banner.title_name)

    @property
    def by_status(self):
        return self.query.order_by(sa.desc(Banner.status))

    @property
    def by_position(self):
        return self.query.order_by(Banner.position)

    def get_paginator(self, query, page=1):
        query_params = self.request.GET.mixed()

        def url_maker(link_page):
            # replace page param with values generated by paginator
            query_params['page'] = link_page
            return self.request.current_route_url(_query=query_params)

        return SqlalchemyOrmPage(query, page, items_per_page=2, url_maker=url_maker)
