from carusel.models.banner import Banner
import sqlalchemy as sa
from paginate_sqlalchemy import SqlalchemyOrmPage


class CaruselPaginationService():

    @classmethod
    def all(cls, request):
        query = request.dbsession.query(Banner)
        return query.order_by(sa.desc(Banner.created))

    @classmethod
    def by_title_name(cls, request):
        query = request.dbsession.query(Banner)
        return query.order_by(Banner.title_name)

    @classmethod
    def by_status(cls, request):
        query = request.dbsession.query(Banner)
        return query.order_by(sa.desc(Banner.status))

    @classmethod
    def by_position(cls, request):
        query = request.dbsession.query(Banner)
        return query.order_by(sa.desc(Banner.position))

    @classmethod
    def get_paginator(cls, request, page=1):
        query = request.dbsession.query(Banner)
        query = query.order_by(sa.desc(Banner.created))
        query_params = request.GET.mixed()

        def url_maker(link_page):
            # replace page param with values generated by paginator
            query_params['page'] = link_page
            return request.current_route_url(_query=query_params)

        return SqlalchemyOrmPage(query, page, items_per_page=2, url_maker=url_maker)
